config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'get_currencies', to: 'currencies#get_currencies', as: 'get_currencies'

  root 'currencies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/currencies_controller.rb
require 'open-uri'

class CurrenciesController < ApplicationController

  helper_method :convert_currency

  DATA_URL = 'http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml'
  RATE_ROUND_PRECISION = 4

  def index
    @currencies = ExchangeRate::Record.select(:currency).distinct
    if params[:date]
      @date = params[:date][:date]
    end
    @amount = params[:amount]
    @from = params[:from]
    @to = params[:to]

    if !@date.nil? && !@from.nil? && !@to.nil?
      @answer = (ExchangeRate::Rate.instance.at(@date, @from, @to) * @amount.to_f).round(RATE_ROUND_PRECISION)
    end
    respond_to do |format|
      format.html { render :index }
      format.js
    end
  end

  # Fetches xml data from source and updates the database if needed
  def get_currencies
    @last_updated = ExchangeRate::Record.maximum('date');
    xml = Hash.from_xml(open(DATA_URL))
    n = xml['Envelope']['Cube']['Cube'].count
    (0..n-1).each do |i|
      @date = xml['Envelope']['Cube']['Cube'][i]['time'];
      @data = xml['Envelope']['Cube']['Cube'][i]['Cube'];
      if @last_updated.nil? || @last_updated < Date.parse(@date)
        @data.each do |rate|
          p "#{@date} #{rate["currency"]} #{rate["rate"]}"
          ExchangeRate::Rate.instance.set(rate['currency'], rate['rate'], @date)
        end
        ExchangeRate::Rate.instance.set('EUR', 1.0, @date)
      end
    end
    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_tag(root_path, remote: true, method: :get) do %>
      <div class="form-group">
        <label>Date</label>
        <%= date_field :date, :date, value: @date || Date.today, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Amount</label>
        <%= number_field_tag :amount, @amount || '0', class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>From</label>
        <%= select_tag :from, options_from_collection_for_select(@currencies, :currency, :currency, @from || 'GBP'), { class: 'form-control'} %>
      </div>
      <div class="form-group">
        <label>To</label>
        <%= select_tag :to, options_from_collection_for_select(@currencies, :currency, :currency, @to || 'USD'), { class: 'form-control'} %>
      </div>

      <div class="row">
        <div class="col-md-2">
          <a onclick="swapCurrencies()" class="btn btn-outline-primary btn-lg btn-block" id="swap-currencies-button" title="Swap currencies">Swap</a>
        </div>
        <div class="col-md-8">
          <button type="submit" class="btn btn-primary btn-lg btn-block">Convert</button>
        </div>
        <div class="col-md-2">
          <%= link_to '', get_currencies_path, class: 'btn btn-outline-primary side-button', id: 'reload-data-button', title: 'Reload data' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row" id="answer-container">
  <div class="col-md-12">
    <div class="card">
      <h4 class="card-header">Answer</h4>
      <div id="answer" class="card-block">
        <% if @answer %>
            <p class="card-text text-center"><%= @answer %></p>
        <% else %>
            <p class="card-text text-center">0</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/currencies/index.js.erb
$('#answer').html("<p class='card-text text-center'><%= @answer %></p>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foreign Exchange</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" style="margin-top: 50px">
      <div class="row">
        <div class="col-md-12">
          <h2 class="text-center">iFX</h2>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>